/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8WlDNzXmVN0
 */
import Link from "next/link";
import Image from "next/image";
import { CardContent, Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "./ui/tooltip";
import Head from "next/head";

export function Landing() {
  return (
    <>
      <Head>
        <title>BRHS Bloom Institute</title>
      </Head>
      <div key="1" className="flex flex-col min-h-[100vh]">
        <header className="px-4 lg:px-6 h-14 flex items-center">
          <Link className="flex items-center justify-center" href="#">
            <SchoolIcon className="h-6 w-6" />
            <span className="ml-2 text-lg font-semibold">Bloom Institute</span>
            <span className="sr-only">Bloom Institute</span>
          </Link>
          <nav className="ml-auto flex gap-4 sm:gap-6">
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#events"
            >
              Events
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="//bloominst.org"
            >
              HQ
            </Link>
          </nav>
        </header>
        <main className="flex-1">
          <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
            <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
              <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
                <div>
                  <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                    Building Bright Futures for High School Students
                  </h1>
                </div>
                <div className="flex flex-col items-start space-y-4">
                  <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                    Bloom Institute is dedicated to empowering high school
                    students with the skills and opportunities to kickstart
                    their careers. Join us in making a difference.
                  </p>
                  <div className="space-x-4">
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                      href="#"
                    >
                      Get Involved
                    </Link>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                      href="#"
                    >
                      Learn More
                    </Link>
                  </div>
                </div>
              </div>
              <Image
                alt="Career Development"
                className="mx-auto aspect-[3/1] overflow-hidden rounded-t-xl object-cover"
                height="300"
                src="/career-development.jpg"
                width="1270"
              />
            </div>
          </section>
          <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
            <div className="container space-y-12 px-4 md:px-6">
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                    Our Mission
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Empowering Students, Building Careers
                  </h2>
                  <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    At Bloom Institute, we believe in the potential of every
                    high school student. Our programs are designed to provide
                    students with the skills, resources, and opportunities they
                    need to build successful careers.
                  </p>
                </div>
              </div>
              <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Career Guidance</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our career guidance program helps students explore different
                    career paths and make informed decisions about their future.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Skill Development</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    We offer a range of skill development programs to equip
                    students with the skills they need to succeed in their
                    chosen careers.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">
                    Internship Opportunities
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our partnerships with local businesses provide students with
                    valuable internship opportunities to gain practical
                    experience.
                  </p>
                </div>
              </div>
            </div>
          </section>
          <section className="w-full py-12 md:py-24 lg:py-32">
            <div className="container px-4 md:px-6">
              <div className="flex flex-col items-center justify-center space-y-8 text-center mb-10">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                    Meet Our Team
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Our Dedicated Team
                  </h2>
                  <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    Meet the dedicated team behind Bloom Institute. Each member
                    brings their unique skills and passion to our mission of
                    empowering students.
                  </p>
                </div>
              </div>
              <div className="mx-auto grid items-start gap-4 sm:max-w-4xl sm:grid-cols-2 md:gap-6 lg:max-w-5xl lg:grid-cols-3">
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 1"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/SAKETH_BONGU.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Saketh Bongu</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      President
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Average guy who likes to sleep.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 2"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/AMULYA_BISARIA.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Amulya Bisaria</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Vice President
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      philosopher.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 3"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/MOHIT_SRINIVASAN.png"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Mohit Srinivasan</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Webmaster
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Insert something funny here.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 4"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/ARYA_VAIDYA.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Arya Vaidya</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Webmaster
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      My brother went to Princeton.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 5"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/AYUSHMAAN_MUKHERJEE.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Ayushmaan Mukherjee</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Treasurer
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      I love doing Model UN and public forum debate. Also,
                      history, current events, and reading.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 6"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/DAKSH_RAJPUT.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Daksh Rajput</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Treasurer
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      I like playing volleyball and doing outdoor activities
                      while enjoying a weird music taste.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 7"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/JACKSON_FRANKLIN.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Jackson Franklin</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Outreach
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      &quot;Before you run with the bag you gotta walk a lil
                      bit&quot; — Babytron.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 8"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/GRANT_DEQUINA.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Grant Dequina</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Outreach
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      I like to do a lot of different things, only in mediocrity
                      though.
                    </p>
                  </CardContent>
                </Card>
                <Card className="h-[20rem]">
                  <CardContent className="flex flex-col justify-center items-center h-full gap-1">
                    <Image
                      alt="Team Member 8"
                      className="mx-auto aspect-[1/1] overflow-hidden rounded-full object-cover"
                      height="140"
                      src="/people/ROHIT_MUDDULURU.jpg"
                      width="140"
                    />
                    <h3 className="text-lg font-bold">Rohit Mudduluru</h3>
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400">
                      Outreach
                    </p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      better philosopher then Amulya.
                    </p>
                  </CardContent>
                </Card>
              </div>
            </div>
          </section>
          <section
            className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
            id="events"
          >
            <div className="container space-y-12 px-4 md:px-6">
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                    Upcoming Events
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Join Our Events
                  </h2>
                  <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    We host a variety of events throughout the year. Join us to
                    learn more about our programs and meet our team.
                  </p>
                </div>
              </div>
              <div className="mx-auto items-start gap-8 sm:max-w-4xl grid-rows-2 sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                <Card className="h-full w-full grid grid-cols-2 gap-2">
                  <Image
                    alt="Event Image"
                    className="aspect-rectangle object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                    height={140}
                    src="/career-faira.jpg"
                    width={140}
                  />
                  <CardContent className="flex flex-col space-y-5 justify-center">
                    <h3 className="text-lg font-bold">Career Fair 2024</h3>
                    <div className="flex gap-2">
                      <Badge variant="secondary">March 15, 2024</Badge>
                      <Badge variant="secondary">Bloom Institute HQ</Badge>
                    </div>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Join us for our annual career fair. Meet representatives
                      from various industries and explore potential career
                      paths.
                    </p>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger>
                          <Link
                            className="inline-flex disabled h-9 w-full items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                            href="/"
                          >
                            Register Now
                          </Link>
                        </TooltipTrigger>
                        <TooltipContent>
                          Currently unavailable, as the date is not finalized.
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </CardContent>
                </Card>
              </div>
            </div>
          </section>

          <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              © Bloom Institute. All rights reserved.
            </p>
            <nav className="sm:ml-auto flex gap-4 sm:gap-6">
              <Link
                className="text-xs hover:underline underline-offset-4"
                href="//instagram.com/bloominstitute_brhs"
              >
                Instagram
              </Link>
            </nav>
          </footer>
        </main>
      </div>
    </>
  );
}

function SchoolIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m4 6 8-4 8 4" />
      <path d="m18 10 4 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8l4-2" />
      <path d="M14 22v-4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v4" />
      <path d="M18 5v17" />
      <path d="M6 5v17" />
      <circle cx="12" cy="9" r="2" />
    </svg>
  );
}
